// ==========================================================
// SACH YA JHOOT — Questions Data File
// ==========================================================
// Har question ek object hai is format mein:
//   { hi: "Hindi wala text", en: "English wala text", category: "mild" | "spicy" | "extreme" }
//
// NAYA QUESTION ADD KARNA HO TO:
// 1. Neeche truthQuestions ya dareQuestions array mein
// 2. Ek naya { hi: "...", en: "...", category: "..." } object jodo (comma lagana mat bhoolna)
// 3. category sirf teen values mein se ek honi chahiye: "mild", "spicy", "extreme"
//
// Bas itna hi — index.html ko touch karne ki zaroorat nahi.
// ==========================================================

const truthQuestions = [
  // ---------- MILD ----------
  { hi: "Aapki sabse embarrassing memory kya hai jo aapne kisi ko nahi batayi?", en: "What's your most embarrassing memory that you've never told anyone?", category: "mild" },
  { hi: "Aapke phone mein sabse ajeeb screenshot kaunsa hai?", en: "What's the weirdest screenshot saved in your phone?", category: "mild" },
  { hi: "Sabse embarrassing song jo aap akele mein gate ho?", en: "What's the most embarrassing song you sing when you're alone?", category: "mild" },
  { hi: "Aapka weirdest search history mein kya hai jo yaad hai?", en: "What's the weirdest thing in your search history that you remember?", category: "mild" },

    { hi: "Aapka sabse favourite bachpan ka khilona kya tha?", en: "What was your favorite childhood toy?", category: "mild" },
  { hi: "Aap ek din ke liye invisible ho sakte ho to kya karoge?", en: "If you could be invisible for a day, what would you do?", category: "mild" },
  { hi: "Aapki sabse pasandida movie kaunsi hai jo aap baar baar dekh sakte ho?", en: "What's your favorite movie that you can watch again and again?", category: "mild" },
  { hi: "Aapko kaunsa khana bilkul pasand nahi hai?", en: "What food do you absolutely dislike?", category: "mild" },
  { hi: "Aap subah uthke sabse pehle kya karte ho?", en: "What's the first thing you do after waking up?", category: "mild" },
  { hi: "Aapka sabse ajeeb dar (fear) kya hai?", en: "What's your weirdest fear?", category: "mild" },
  { hi: "Agar aapko ek superpower milta to kaunsa chahoge?", en: "If you could have one superpower, what would it be?", category: "mild" },
  { hi: "Aapne kabhi apne aap se baat ki hai zor se? Kab?", en: "Have you ever talked to yourself out loud? When?", category: "mild" },
  { hi: "Aapka favourite school subject kya tha?", en: "What was your favorite subject in school?", category: "mild" },
  { hi: "Kya aap kabhi kisi cartoon character ki tarah banna chahte the?", en: "Did you ever want to be like a cartoon character?", category: "mild" },
  { hi: "Aapko sabse zyada kaunsa mausam pasand hai?", en: "What's your favorite weather?", category: "mild" },
  { hi: "Aap ghar pe akele ho to sabse pehle kya karte ho?", en: "What's the first thing you do when you're home alone?", category: "mild" },
  { hi: "Aapka koi ajeeb talent hai jo kisi ko pata nahi?", en: "Do you have a weird talent that no one knows about?", category: "mild" },
  { hi: "Aap kaunsa animal banna chahoge agar ek din ke liye mauka mile?", en: "What animal would you want to become for a day?", category: "mild" },
  { hi: "Aapki sabse purani yaad kya hai jo yaad hai?", en: "What's your earliest memory that you can recall?", category: "mild" },
  { hi: "Aap kaunsi jagah ghumne jaana chahte ho jo abhi tak nahi gaye?", en: "Which place do you want to visit that you haven't been to yet?", category: "mild" },
  { hi: "Aapka favourite festival kaunsa hai aur kyun?", en: "What's your favorite festival and why?", category: "mild" },
  { hi: "Aapne kabhi kisi cheez ko lekar bahut zyada overthink kiya ho?", en: "Have you ever overthought something way too much?", category: "mild" },
  { hi: "Aap kaunsa gaana sunke turant dance karne lagte ho?", en: "What song makes you dance immediately when you hear it?", category: "mild" },
  { hi: "Kya aapko andhera pasand hai ya roshni?", en: "Do you prefer darkness or light?", category: "mild" },
  { hi: "Aapki sabse bewakoofi wali harkat kya thi bachpan mein?", en: "What was your silliest habit as a kid?", category: "mild" },
  { hi: "Aap chai pite ho ya coffee, aur kyun?", en: "Do you drink tea or coffee, and why?", category: "mild" },
  { hi: "Aapko kaunsa emoji sabse zyada use karna pasand hai?", en: "Which emoji do you use the most?", category: "mild" },
  { hi: "Agar aapko ek din ke liye teacher banna pade to kya sikhaoge?", en: "If you had to be a teacher for a day, what would you teach?", category: "mild" },
  { hi: "Aapka favourite street food kya hai?", en: "What's your favorite street food?", category: "mild" },
  { hi: "Aap kis cheez se sabse jaldi hasne lagte ho?", en: "What makes you laugh the fastest?", category: "mild" },
  { hi: "Aapko kaunsa season sabse zyada pasand hai — garmi, sardi ya barsaat?", en: "Which season do you like most — summer, winter, or rain?", category: "mild" },
  { hi: "Aap apne phone mein sabse zyada kaunsa app use karte ho?", en: "Which app do you use the most on your phone?", category: "mild" },
  { hi: "Aapka sabse pasandida cartoon ya anime kaunsa tha?", en: "What was your favorite cartoon or anime?", category: "mild" },
  { hi: "Aap kabhi khud pe hansi aayi ho kisi cheez pe? Kab?", en: "Have you ever laughed at yourself about something? When?", category: "mild" },
  { hi: "Aapko kaunsi cheez sabse jaldi bore kar deti hai?", en: "What bores you the fastest?", category: "mild" },
  { hi: "Aap sote waqt kaunsi position mein sote ho?", en: "What position do you sleep in?", category: "mild" },
  { hi: "Aapko kaunsa color sabse zyada pasand hai aur kyun?", en: "What's your favorite color and why?", category: "mild" },
  { hi: "Aapne kabhi kisi cheez ko galat naam se pukara ho public mein?", en: "Have you ever called something by the wrong name in public?", category: "mild" },
  { hi: "Aap kaunsa game sabse zyada khelte ho apne phone pe?", en: "What game do you play the most on your phone?", category: "mild" },
  { hi: "Aapka favourite dessert/mithai kaunsi hai?", en: "What's your favorite dessert/sweet?", category: "mild" },
  { hi: "Aap kabhi kisi cheez ko dhoondte hue wahi haath mein thi, aisa hua hai?", en: "Have you ever searched for something that was in your hand the whole time?", category: "mild" },
  { hi: "Aapko kaunsa subject sabse mushkil lagta tha school mein?", en: "Which subject felt hardest to you in school?", category: "mild" },
  { hi: "Aap kaunsi movie dekh ke sabse zyada roye ho?", en: "Which movie made you cry the most?", category: "mild" },
  { hi: "Aapka pehla pet ka naam kya tha (agar tha to)?", en: "What was your first pet's name (if you had one)?", category: "mild" },
  { hi: "Aap kis cheez ke liye sabse zyada procrastinate karte ho?", en: "What do you procrastinate the most on?", category: "mild" },
  { hi: "Aapko kaunsi jagah sabse peaceful lagti hai?", en: "Which place feels the most peaceful to you?", category: "mild" },
  { hi: "Aap apne favourite singer/band ka naam batao", en: "Name your favorite singer/band", category: "mild" },
  { hi: "Aapko kaunsa festival food sabse zyada pasand hai?", en: "What's your favorite festival food?", category: "mild" },
  { hi: "Aap kaunsi cheez collect karte ho ya karna chahte ho?", en: "What do you collect or wish to collect?", category: "mild" },
  { hi: "Aapko subah jaldi uthna pasand hai ya raat ko jagna?", en: "Do you prefer waking up early or staying up late?", category: "mild" },
  { hi: "Aap kis film ke character jaisa banna chahoge?", en: "Which movie character would you want to be like?", category: "mild" },
  { hi: "Aapko kaunsa smell sabse zyada pasand hai?", en: "What smell do you like the most?", category: "mild" },
  { hi: "Aap kaunsa hobby seekhna chahte ho jo abhi nahi aata?", en: "What hobby do you want to learn that you don't know yet?", category: "mild" },
  { hi: "Aapki sabse pasandida book/comic kaunsi hai?", en: "What's your favorite book/comic?", category: "mild" },
  { hi: "Aap kaunsi cheez sabse zyada save karke rakhte ho apne phone mein?", en: "What do you save the most on your phone?", category: "mild" },
  { hi: "Aapko lagta hai aap subah wale ho ya raat wale?", en: "Do you think you're a morning person or a night person?", category: "mild" },
  { hi: "Aap kaunsa sport dekhna pasand karte ho?", en: "What sport do you like watching?", category: "mild" },
  { hi: "Aapka sabse pasandida chhutti (vacation) kaunsi thi?", en: "What was your favorite vacation?", category: "mild" },
  { hi: "Aap kaunsi cheez roz karte ho bina soche?", en: "What do you do every day without thinking about it?", category: "mild" },
  { hi: "Aapko kaunsa dessert banana aata hai?", en: "What dessert do you know how to make?", category: "mild" },
  { hi: "Aap kis cheez ke liye sabse zyada excited rehte ho?", en: "What are you most excited about these days?", category: "mild" },
  { hi: "Aapka favourite outfit/dress kaunsa hai?", en: "What's your favorite outfit?", category: "mild" },
  { hi: "Aap kaunsi language aur seekhna chahte ho?", en: "What other language do you want to learn?", category: "mild" },
  { hi: "Aapko kaunsa sound sabse annoying lagta hai?", en: "What sound annoys you the most?", category: "mild" },
  { hi: "Aap kaunsa chhota kaam karne mein sabse zyada aalas karte ho?", en: "What small task do you procrastinate on the most?", category: "mild" },
  { hi: "Aapki sabse pasandida photo kaunsi hai jo aapne khichi ho?", en: "What's your favorite photo that you've taken?", category: "mild" },
  { hi: "Aap kis cheez pe sabse zyada paisa kharch karte ho?", en: "What do you spend the most money on?", category: "mild" },
  { hi: "Aapko kaunsa naya skill seekhna hai is saal?", en: "What new skill do you want to learn this year?", category: "mild" },
  { hi: "Aap kaunsi cheez khud pakate ho sabse achhi?", en: "What's the best dish you can cook yourself?", category: "mild" },
  { hi: "Aapko kaunsa show binge-watch karna pasand hai?", en: "What show do you like binge-watching?", category: "mild" },
  { hi: "Aap kaunsi cheez apne bag/pocket mein hamesha rakhte ho?", en: "What do you always carry in your bag/pocket?", category: "mild" },
  { hi: "Aapka favourite childhood snack kya tha?", en: "What was your favorite childhood snack?", category: "mild" },
  { hi: "Aap kis cheez ke liye sabse zyada thankful ho abhi?", en: "What are you most thankful for right now?", category: "mild" },
  { hi: "Aapko kaunsa instrument bajana aata hai ya seekhna hai?", en: "What instrument can you play or want to learn?", category: "mild" },
  { hi: "Aap kaunsi jagah pe sabse zyada relax feel karte ho?", en: "Where do you feel most relaxed?", category: "mild" },
  { hi: "Aapki phone ki lock screen pe kya hai abhi?", en: "What's currently on your phone's lock screen?", category: "mild" },
  { hi: "Aap kis cheez ke liye jaldi tayaar ho jaate ho?", en: "What are you quick to get ready for?", category: "mild" },
  { hi: "Aapko kaunsa comfort food sabse zyada pasand hai?", en: "What's your favorite comfort food?", category: "mild" },
  { hi: "Aap kaunsi cheez roz check karte ho phone mein sabse pehle?", en: "What's the first thing you check on your phone daily?", category: "mild" },
  { hi: "Aapka favourite subject tha ya hai jo aapko easy lagta hai?", en: "What's/was your favorite subject that felt easy to you?", category: "mild" },
  { hi: "Aap kis cheez ko lekar bahut particular ho?", en: "What are you very particular about?", category: "mild" },
  { hi: "Aapko kaunsa junk food sabse zyada pasand hai?", en: "What's your favorite junk food?", category: "mild" },
  { hi: "Aap kaunsi cheez apne kamre mein sabse zyada dekhte ho?", en: "What do you look at the most in your room?", category: "mild" },
  { hi: "Aapka favourite weekend plan kya hota hai?", en: "What's your favorite weekend plan?", category: "mild" },
  { hi: "Aap kis cheez ke expert ho apne dosto ke beech?", en: "What are you the 'expert' at among your friends?", category: "mild" },
  { hi: "Aapko kaunsa season ka fruit sabse zyada pasand hai?", en: "What's your favorite seasonal fruit?", category: "mild" },
  { hi: "Aap kaunsi cheez baar baar dekhte/sunte nahi thakte?", en: "What can you watch/listen to repeatedly without getting bored?", category: "mild" },
  { hi: "Aapka favourite subject tha jo aapko bore karta tha?", en: "What was a subject that used to bore you?", category: "mild" },
  { hi: "Aap kis cheez pe sabse zyada gaurav (proud) feel karte ho?", en: "What are you proudest of?", category: "mild" },
  { hi: "Aapko kaunsa gaana bachpan se yaad hai?", en: "What song do you remember from childhood?", category: "mild" },
  { hi: "Aap kaunsi cheez dekh ke turant khush ho jaate ho?", en: "What instantly makes you happy when you see it?", category: "mild" },
  { hi: "Aapka favourite ice cream flavour kya hai?", en: "What's your favorite ice cream flavor?", category: "mild" },
  { hi: "Aap kis cheez ko lekar sabse zyada curious rehte ho?", en: "What are you most curious about?", category: "mild" },
  { hi: "Aapko kaunsi cheez easily impress kar deti hai?", en: "What easily impresses you?", category: "mild" },
  { hi: "Aap kaunsi jagah baar baar jaana chahte ho?", en: "Which place do you want to visit again and again?", category: "mild" },
  { hi: "Aapka favourite subject line kya hoga agar aap teacher ho?", en: "If you were a teacher, what would your favorite topic to teach be?", category: "mild" },
  { hi: "Aap kis cheez ke liye sabse zyada patience rakhte ho?", en: "What are you most patient about?", category: "mild" },
  { hi: "Aapko kaunsa outfit pehen ke sabse confident lagta hai?", en: "Which outfit makes you feel most confident?", category: "mild" },
  { hi: "Aap kaunsi cheez sabse zyada miss karte ho bachpan ki?", en: "What do you miss the most from childhood?", category: "mild" },
  { hi: "Aapka favourite time of day kaunsa hai?", en: "What's your favorite time of day?", category: "mild" },
  { hi: "Aap kis cheez ke liye sabse zyada grateful feel karte ho aaj?", en: "What are you most grateful for today?", category: "mild" },
  { hi: "Aapko kaunsa hobby sabse zyada relaxing lagta hai?", en: "Which hobby feels most relaxing to you?", category: "mild" },
  { hi: "Aap kaunsi cheez pehli baar try karna chahoge?", en: "What would you like to try for the first time?", category: "mild" },

// ---------- SPICY ----------
  { hi: "Kya kabhi kisi teacher pe crush hua tha?", en: "Have you ever had a crush on a teacher?", category: "spicy" },
  { hi: "Is room mein kiska crush hone ka sabse zyada chance hai?", en: "Who in this room is most likely to have a crush on someone here?", category: "spicy" },
  { hi: "Sach batao — aap apne ex ka Instagram kitni baar stalk karte ho?", en: "Be honest — how often do you stalk your ex's Instagram?", category: "spicy" },
  { hi: "Kya kabhi crush ke saamne bewakoofi ki ho aur wo abhi tak yaad ho?", en: "Have you ever embarrassed yourself in front of your crush that you still remember?", category: "spicy" },

    { hi: "Aapki last relationship khatam hone ki asli wajah kya thi?", en: "What was the real reason your last relationship ended?", category: "spicy" },
  { hi: "Aapne kisi ko like kiya ho aur wo aapke best friend ko pasand karta ho — aisa hua hai?", en: "Have you ever liked someone who liked your best friend instead?", category: "spicy" },
  { hi: "Aapka phone kisi ko dena pada aur wo aapki chats dekh le — sabse zyada dar kis cheez ka lagega?", en: "If someone had to see your phone chats, what would you be most scared they'd find?", category: "spicy" },
  { hi: "Kya aapne kabhi kisi ko unfollow kiya sirf jealousy ki wajah se?", en: "Have you ever unfollowed someone purely out of jealousy?", category: "spicy" },
  { hi: "Aapne kabhi kisi crush ko dekhne ke liye jaan boojh kar plan banaya ho unse milne ka?", en: "Have you ever made a plan just to accidentally-on-purpose run into your crush?", category: "spicy" },
  { hi: "Kya aap kabhi kisi ke saath jealous hue ho jab wo kisi aur se baat kar raha tha?", en: "Have you ever felt jealous watching someone talk to another person?", category: "spicy" },
  { hi: "Aapne apne crush ke bare mein sabse bada jhoot khud se kya bola hai?", en: "What's the biggest lie you've told yourself about your crush?", category: "spicy" },
  { hi: "Kya aapne kisi ka status/story sirf isliye dekha kyunki wo interesting person ki thi?", en: "Have you ever viewed someone's story just because you find them interesting?", category: "spicy" },
  { hi: "Aapko is group mein sabse zyada kaunsa secret pata hai jo kisi ko nahi pata?", en: "What secret about someone in this group do you know that no one else does?", category: "spicy" },
  { hi: "Kya kisi ne kabhi aapko propose kiya ho jise aapne reject kiya?", en: "Has anyone ever proposed to you that you rejected?", category: "spicy" },
  { hi: "Aap kisi ka number nikaalne ke liye kitni far ja sakte ho?", en: "How far would you go to get someone's number?", category: "spicy" },
  { hi: "Kya aapne kabhi apne crush ki taareef ki ho unse aankh milaye bina?", en: "Have you ever complimented your crush without making eye contact?", category: "spicy" },
  { hi: "Aapko kisne aakhri baar 'I like you' bola tha?", en: "Who was the last person to tell you 'I like you'?", category: "spicy" },
  { hi: "Kya aapne kabhi kisi ke liye apna plan cancel kiya bina bataye kyun?", en: "Have you ever canceled a plan for someone without telling them the real reason?", category: "spicy" },
  { hi: "Aapko sabse zyada attractive kaunsi cheez lagti hai kisi mein?", en: "What quality do you find most attractive in someone?", category: "spicy" },
  { hi: "Kya kabhi aapne apne crush ka number save karke naam kuch aur rakha ho?", en: "Have you ever saved your crush's number under a different name?", category: "spicy" },
  { hi: "Aap kis type ki personality ki taraf sabse jaldi attract hote ho?", en: "What kind of personality are you most quickly attracted to?", category: "spicy" },
  { hi: "Kya kabhi aapko lagta hai koi aapko like karta hai but aapne ignore kiya?", en: "Have you ever felt someone liked you but you ignored it?", category: "spicy" },
  { hi: "Aapka sabse embarrassing DM kisko gaya tha galti se?", en: "What was the most embarrassing DM you accidentally sent to the wrong person?", category: "spicy" },
  { hi: "Kya aap kabhi kisi crush ke social media pe active rehte ho unko impress karne ke liye?", en: "Have you ever stayed active on social media just to get your crush's attention?", category: "spicy" },
  { hi: "Aapko lagta hai is room mein sabse zyada flirty kaun hai?", en: "Who do you think is the flirtiest person in this room?", category: "spicy" },
  { hi: "Kya kabhi aapne kisi ka photo dekh ke unse baat karne ki himmat nahi hui?", en: "Have you ever seen someone's photo and been too shy to talk to them?", category: "spicy" },
  { hi: "Aap kisi crush ko impress karne ke liye kya jhoot bol sakte ho?", en: "What lie would you tell to impress a crush?", category: "spicy" },
  { hi: "Kya aapne kabhi kisi ke liye apna style ya habits change kiye ho?", en: "Have you ever changed your style or habits for someone?", category: "spicy" },
  { hi: "Aapko sabse zyada kaunsi cheez turn off karti hai kisi mein?", en: "What's your biggest turn-off in a person?", category: "spicy" },
  { hi: "Kya aapne kabhi apne dost ke crush ko like kiya ho bina unhe bataye?", en: "Have you ever liked your friend's crush without telling them?", category: "spicy" },
  { hi: "Aap first date pe sabse zyada nervous kis wajah se hote ho?", en: "What makes you most nervous on a first date?", category: "spicy" },
  { hi: "Kya kabhi aapne kisi ke liye late night tak baat ki ho bina sone ke?", en: "Have you ever stayed up all night talking to someone?", category: "spicy" },
  { hi: "Aapko lagta hai aap kisi ke liye 'red flag' ho kis wajah se?", en: "In what way do you think you might be a 'red flag' for someone?", category: "spicy" },
  { hi: "Kya aapne kabhi kisi ko dekh ke apna crush change kiya ho turant?", en: "Have you ever instantly changed your crush after seeing someone else?", category: "spicy" },
  { hi: "Aap kisi crush ke reply na aane pe kitna overthink karte ho?", en: "How much do you overthink when your crush doesn't reply?", category: "spicy" },
  { hi: "Kya kabhi aapne apne crush ke friend se unke bare mein poocha ho?", en: "Have you ever asked your crush's friend about them?", category: "spicy" },
  { hi: "Aapko sabse zyada romantic gesture kaunsa lagta hai?", en: "What's the most romantic gesture to you?", category: "spicy" },
  { hi: "Kya aapne kabhi kisi ka photo dekh ke unko turant follow kiya ho?", en: "Have you ever followed someone instantly just from seeing their photo?", category: "spicy" },
  { hi: "Aap kis umar mein pehli baar kisi ko like kiya tha?", en: "At what age did you first like someone romantically?", category: "spicy" },
  { hi: "Kya kabhi aapne apne crush ke saamne apni image better dikhane ki koshish ki ho?", en: "Have you ever tried to appear better than you are in front of your crush?", category: "spicy" },
  { hi: "Aapko lagta hai aap jaldi pyaar mein padte ho ya der se?", en: "Do you think you fall in love quickly or slowly?", category: "spicy" },
  { hi: "Kya aapne kabhi kisi crush ki galti ko ignore kiya sirf isliye kyunki aap unhe pasand karte the?", en: "Have you ever ignored your crush's mistake just because you liked them?", category: "spicy" },
  { hi: "Aapka sabse bada 'almost relationship' kiske saath tha?", en: "Who was your biggest 'almost relationship'?", category: "spicy" },
  { hi: "Kya kabhi aap kisi ko like karte the aur pata chala unka kisi aur mein interest hai?", en: "Have you ever liked someone and found out they were interested in someone else?", category: "spicy" },
  { hi: "Aap kisi ke saath first meet mein sabse zyada kya notice karte ho?", en: "What's the first thing you notice about someone you meet?", category: "spicy" },
  { hi: "Kya aapne kabhi apne crush ke bare mein apne dost se jhoot bola ho?", en: "Have you ever lied to your friend about your crush?", category: "spicy" },
  { hi: "Aapko lagta hai is group mein sabse pehle relationship mein kaun aayega?", en: "Who in this group do you think will get into a relationship first?", category: "spicy" },
  { hi: "Kya kabhi aapne kisi ko block kiya sirf isliye kyunki wo aapko like karta tha?", en: "Have you ever blocked someone just because they liked you?", category: "spicy" },
  { hi: "Aap apne crush ke messages ka reply kitni der mein dete ho, jaan boojh kar?", en: "How long do you intentionally wait before replying to your crush's messages?", category: "spicy" },
  { hi: "Kya kabhi aapko lagta hai aapne galat time pe sahi insaan ko miss kar diya?", en: "Do you ever feel you missed the right person at the wrong time?", category: "spicy" },
  { hi: "Aapko sabse zyada kis cheez se pata chalta hai ki koi aapme interested hai?", en: "What's the biggest sign that tells you someone is interested in you?", category: "spicy" },
  { hi: "Kya aapne kabhi apne crush ke saath 'accidentally' same jagah hone ki koshish ki ho?", en: "Have you ever tried to 'accidentally' be at the same place as your crush?", category: "spicy" },
  { hi: "Aap kisi rishte mein sabse zyada kis cheez se darte ho?", en: "What do you fear most in a relationship?", category: "spicy" },
  { hi: "Kya kabhi aapne apna crush apne dost se chhupaya ho?", en: "Have you ever hidden your crush from your friends?", category: "spicy" },
  { hi: "Aapko lagta hai aap ek achhe partner banoge, sach mein?", en: "Honestly, do you think you'd make a good partner?", category: "spicy" },
  { hi: "Kya kabhi aapne kisi ke liye apna number change nahi kiya sirf unke wajah se?", en: "Have you ever kept your number just because of one specific person?", category: "spicy" },
  { hi: "Aap first impression mein sabse zyada kya try karte ho dikhane?", en: "What do you try hardest to show in a first impression?", category: "spicy" },
  { hi: "Kya aapne kabhi kisi crush ke saath imaginary future socha ho?", en: "Have you ever imagined a future with a crush before even dating them?", category: "spicy" },
  { hi: "Aapko lagta hai aap easily heartbreak se recover kar lete ho ya nahi?", en: "Do you think you recover easily from heartbreak or not?", category: "spicy" },
  { hi: "Kya kabhi aapne apni feelings kisi ko batayi na ho sirf dar ki wajah se?", en: "Have you ever kept your feelings to yourself just out of fear?", category: "spicy" },
  { hi: "Aap kisi ke saath crush hone ka pehla sign khud mein kaise pehchante ho?", en: "How do you first realize you have a crush on someone?", category: "spicy" },
  { hi: "Kya kabhi aapko lagta hai aapne kisi ko bahut jaldi trust kar liya?", en: "Have you ever felt you trusted someone too quickly?", category: "spicy" },
  { hi: "Aapko sabse zyada attractive kaunsa habit lagta hai kisi mein?", en: "What habit do you find most attractive in someone?", category: "spicy" },
  { hi: "Kya kabhi aapne apne crush ke liye special playlist banayi ho?", en: "Have you ever made a special playlist for your crush?", category: "spicy" },
  { hi: "Aap kisi ke text ka tone padh ke unki mood guess kar sakte ho?", en: "Can you guess someone's mood just from the tone of their text?", category: "spicy" },
  { hi: "Kya kabhi aapne apna crush kisi se compare kiya ho bina wajah?", en: "Have you ever compared your crush to someone else without reason?", category: "spicy" },
  { hi: "Aapko lagta hai aap possessive nature ke ho relationships mein?", en: "Do you think you're possessive in relationships?", category: "spicy" },
  { hi: "Kya kabhi aapne kisi ko like karna band kiya sirf ek chhoti si baat se?", en: "Have you ever stopped liking someone over one small thing?", category: "spicy" },
  { hi: "Aap kisi ki personal life mein sabse zyada kya jaanna chahte ho?", en: "What do you most want to know about someone's personal life?", category: "spicy" },
  { hi: "Kya kabhi aapko lagta hai koi aapko use kar raha tha attention ke liye?", en: "Have you ever felt someone was using you just for attention?", category: "spicy" },
  { hi: "Aapko lagta hai aap easily jealous ho jaate ho kisi cheez pe?", en: "Do you get easily jealous over something?", category: "spicy" },
  { hi: "Kya kabhi aapne apne crush ke ex ko stalk kiya ho?", en: "Have you ever stalked your crush's ex on social media?", category: "spicy" },
  { hi: "Aap first date pe sabse zyada kya avoid karte ho baat karne se?", en: "What do you avoid talking about on a first date?", category: "spicy" },
  { hi: "Kya kabhi aapne apne feelings ko deny kiya ho khud se bhi?", en: "Have you ever denied your feelings even to yourself?", category: "spicy" },
  { hi: "Aapko lagta hai aap kisi rishtey mein zyada deta ho ya lete ho?", en: "Do you think you give more or take more in a relationship?", category: "spicy" },
  { hi: "Kya kabhi aapne apne crush ke saamne nervous hoke kuch ajeeb bol diya ho?", en: "Have you ever gotten nervous and said something weird in front of your crush?", category: "spicy" },
  { hi: "Aap kisi ke saath connection feel karne ke liye kya cheez sabse zaroori maanate ho?", en: "What do you think is most essential to feel a connection with someone?", category: "spicy" },
  { hi: "Kya kabhi aapne kisi crush ka reply padh ke uska matlab overanalyze kiya ho?", en: "Have you ever overanalyzed the meaning of your crush's reply?", category: "spicy" },
  { hi: "Aapko lagta hai aap easily move on kar lete ho ya der lagti hai?", en: "Do you think you move on easily or does it take time for you?", category: "spicy" },
  { hi: "Kya kabhi aap apne crush ke bare mein sapne dekh chuke ho?", en: "Have you ever dreamed about your crush?", category: "spicy" },
  { hi: "Aapko lagta hai aapke friends aapko relationship advice ke liye trust karte hai?", en: "Do you think your friends trust your relationship advice?", category: "spicy" },
  { hi: "Kya kabhi aapne apne crush ke naam pe kisi ki taareef ki ho unki jagah?", en: "Have you ever complimented someone thinking of your crush instead?", category: "spicy" },
  { hi: "Aap first crush ka naam yaad hai? Kaun tha?", en: "Do you remember your first crush's name? Who was it?", category: "spicy" },
  { hi: "Kya kabhi aapko lagta hai aap ek toxic trait rakhte ho relationships mein?", en: "Do you think you have one toxic trait in relationships?", category: "spicy" },
  { hi: "Aapko lagta hai aap kisi ki love language easily samajh sakte ho?", en: "Do you think you can easily understand someone's love language?", category: "spicy" },
  { hi: "Kya kabhi aapne apne crush ko dekh ke apna route change kiya ho?", en: "Have you ever changed your route just to see your crush?", category: "spicy" },
  { hi: "Aap kisi ke bare mein 'type' hai ya nahi hai — kaise decide karte ho?", en: "How do you decide if someone is or isn't your 'type'?", category: "spicy" },
  { hi: "Kya kabhi aapne apne crush ki har story turant dekhi ho notification aate hi?", en: "Have you ever watched your crush's story the instant the notification came?", category: "spicy" },
  { hi: "Aapko lagta hai aap emotionally kitni jaldi attach ho jaate ho?", en: "How quickly do you think you get emotionally attached?", category: "spicy" },
  { hi: "Kya kabhi aapne kisi ko apne crush ke bare mein directly poocha ho unke feelings?", en: "Have you ever directly asked someone about their feelings for your crush?", category: "spicy" },
  { hi: "Aap kisi ke saath baat karte waqt sabse zyada kya observe karte ho unki body language mein?", en: "What do you observe most in someone's body language while talking?", category: "spicy" },
  { hi: "Kya kabhi aapne apne crush ke messages screenshot karke dost ko dikhaye ho?", en: "Have you ever screenshotted your crush's messages to show a friend?", category: "spicy" },
  { hi: "Aapko lagta hai aap first move lene mein confident ho ya shy?", en: "Do you think you're confident or shy about making the first move?", category: "spicy" },
  { hi: "Kya kabhi aapne apna crush kisi film/show ke character se compare kiya ho?", en: "Have you ever compared your crush to a movie/show character?", category: "spicy" },
  { hi: "Aap kisi ki online presence dekh ke unke bare mein kya assume karte ho?", en: "What do you assume about someone just from their online presence?", category: "spicy" },
  { hi: "Kya kabhi aapne apne crush ke liye kuch special plan banaya ho jo kabhi execute nahi hua?", en: "Have you ever made a special plan for your crush that never got executed?", category: "spicy" },
  { hi: "Aapko lagta hai aap kisi rishtey mein communication mein achhe ho ya avoid karte ho?", en: "Do you think you're good at communication in a relationship or do you avoid it?", category: "spicy" },
  { hi: "Kya kabhi aapko lagta hai aap kisi ke liye 'second choice' the?", en: "Have you ever felt you were someone's 'second choice'?", category: "spicy" },
  { hi: "Aap kisi crush ke bare mein sabse zyada kya soch ke sote ho?", en: "What do you think about most regarding a crush before sleeping?", category: "spicy" },
  { hi: "Kya kabhi aapne apna crush kisi ko bataya aur wo unhe accha nahi laga?", en: "Have you ever told someone about your crush and they didn't approve?", category: "spicy" },
  { hi: "Aapko lagta hai aap easily forgive kar dete ho kisi rishtey mein?", en: "Do you forgive easily in a relationship?", category: "spicy" },
  { hi: "Kya kabhi aapne kisi ko like kiya sirf unki ek photo dekh ke?", en: "Have you ever liked someone based on just one photo?", category: "spicy" },
  { hi: "Aapko lagta hai aap kisi ke liye 'obsessed' ho sakte ho? Kis had tak?", en: "Do you think you could get 'obsessed' with someone? To what extent?", category: "spicy" },
  { hi: "Kya kabhi aapne apne crush ke best friend se dosti badhayi ho unke kareeb aane ke liye?", en: "Have you ever befriended your crush's best friend just to get closer?", category: "spicy" },
  { hi: "Aap kisi rishtey mein green flag kya maanate ho sabse zyada?", en: "What do you consider the biggest green flag in a relationship?", category: "spicy" },

// ---------- EXTREME ----------
  { hi: "Sabse bada jhoot jo aapne apne parents se bola ho?", en: "What's the biggest lie you've told your parents?", category: "extreme" },
  { hi: "Kabhi kisi dost ka secret kisi aur ko bata diya ho?", en: "Have you ever told someone else's secret to another person?", category: "extreme" },
  { hi: "Kya kabhi kisi ke bare mein bura socha ho jo aapka close dost hai?", en: "Have you ever thought badly about someone who is your close friend?", category: "extreme" },
  { hi: "Aapka sabse bada regret kya hai is saal ka?", en: "What's your biggest regret from this year?", category: "extreme" },
  { hi: "Aapne kisi dost ki peeth peeche uske bare mein kya bura kaha hai jo aapko yaad hai?", en: "What's the worst thing you've said about a friend behind their back that you remember?", category: "extreme" },
  { hi: "Aapne kabhi kisi rishtedar se jhoot bola ho ek badi baat chhupane ke liye?", en: "Have you ever lied to a relative to hide something big?", category: "extreme" },
  { hi: "Is group mein sabse zyada aap kisse jealous ho aur kyun?", en: "Who in this group are you most jealous of and why?", category: "extreme" },
  { hi: "Aapne kabhi kisi ka trust break kiya ho jaan-boojh kar?", en: "Have you ever intentionally broken someone's trust?", category: "extreme" },
  { hi: "Aapka sabse bada jhoot jo abhi tak kisi ko pata nahi chala?", en: "What's your biggest lie that no one has found out yet?", category: "extreme" },
  { hi: "Kya aapne kabhi kisi ka social media account dekha ho unki permission ke bina?", en: "Have you ever checked someone's social media account without their permission?", category: "extreme" },
  { hi: "Aapne kabhi kisi dost ko intentionally hurt kiya ho, unhe pata bhi na chale ki wo aapne kiya?", en: "Have you ever intentionally hurt a friend without them knowing it was you?", category: "extreme" },
  { hi: "Is group mein aap kisko sabse kam trust karte ho, sach batao?", en: "Honestly, who in this group do you trust the least?", category: "extreme" },
  { hi: "Aapne kabhi kisi ka message dekha ho unse chhupke, bina unhe bataye?", en: "Have you ever read someone's messages secretly without them knowing?", category: "extreme" },
  { hi: "Kya aapne kisi rishte mein cheat kiya ho, physically ya emotionally?", en: "Have you ever cheated in a relationship, physically or emotionally?", category: "extreme" },
  { hi: "Aapko sabse zyada guilt kis cheez ke liye hai jo aapne kisi ke saath ki?", en: "What causes you the most guilt about something you did to someone?", category: "extreme" },
  { hi: "Kya aapne kabhi apne parents se koi badi baat chhupayi hai jo unhe abhi tak pata nahi?", en: "Have you hidden something big from your parents that they still don't know?", category: "extreme" },
  { hi: "Aapne kabhi kisi ke bare mein jaan-boojh kar galat baat failayi ho?", en: "Have you ever intentionally spread a rumor about someone?", category: "extreme" },
  { hi: "Is group mein sabse zyada fake behavior kiska lagta hai aapko?", en: "Who in this group seems the most fake to you?", category: "extreme" },
  { hi: "Kya aapne kabhi kisi close dost ko jaan boojh kar avoid kiya ho bina wajah bataye?", en: "Have you ever intentionally avoided a close friend without explaining why?", category: "extreme" },
  { hi: "Aapne kabhi kisi ki achievement se jealous hoke unhe congratulate nahi kiya ho dil se?", en: "Have you ever felt jealous of someone's achievement and not genuinely congratulated them?", category: "extreme" },
  { hi: "Kya aapne kabhi apne dost ka idea ya kaam khud ka bata diya ho?", en: "Have you ever passed off a friend's idea or work as your own?", category: "extreme" },
  { hi: "Aapka sabse toxic trait kya hai jo aap khud jaante ho?", en: "What's your most toxic trait that you're aware of?", category: "extreme" },
  { hi: "Kya kabhi aapne kisi ko manipulate kiya ho apna kaam nikalwane ke liye?", en: "Have you ever manipulated someone to get something you wanted?", category: "extreme" },
  { hi: "Aapne kabhi kisi rishte ko sirf isliye khatam kiya kyunki koi behtar option mil gaya?", en: "Have you ever ended a relationship just because a better option came along?", category: "extreme" },
  { hi: "Is group mein aap kisse maafi maangna chahte ho kisi purani baat ke liye?", en: "Who in this group would you want to apologize to for something in the past?", category: "extreme" },
  { hi: "Kya aapne kabhi khud ko doosron ke saamne better dikhane ke liye jhoot bola ho?", en: "Have you ever lied to make yourself look better in front of others?", category: "extreme" },
  { hi: "Aapne kabhi kisi ki weakness ka fayda uthaya ho?", en: "Have you ever taken advantage of someone's weakness?", category: "extreme" },
  { hi: "Kya aapko lagta hai aap ek achhe dost ho, sach mein?", en: "Do you honestly think you're a good friend?", category: "extreme" },
  { hi: "Aapne kabhi apne parents ko disappoint kiya ho aur unhe pata bhi nahi chala?", en: "Have you ever disappointed your parents in a way they never found out about?", category: "extreme" },
  { hi: "Kya kabhi aapne kisi close dost se jhoot bola ho unki safety ke bare mein poochne pe?", en: "Have you ever lied to a close friend when they asked about your safety?", category: "extreme" },
  { hi: "Aapko sabse zyada sharam kis baat pe aati hai jo aapne ki thi?", en: "What are you most ashamed of that you've done?", category: "extreme" },
  { hi: "Kya kabhi aapne kisi rishte mein doosre ko blame kiya jo galti aapki thi?", en: "Have you ever blamed the other person in a relationship for a mistake that was yours?", category: "extreme" },
  { hi: "Aapne kabhi kisi ko intentionally jealous banane ki koshish ki ho?", en: "Have you ever intentionally tried to make someone jealous?", category: "extreme" },
  { hi: "Is group mein sabse zyada aapko kaun disappoint karta hai apni harkaton se?", en: "Who in this group disappoints you most with their actions?", category: "extreme" },
  { hi: "Kya aapne kabhi kisi ki family ke bare mein bura socha ho?", en: "Have you ever thought badly about someone's family?", category: "extreme" },
  { hi: "Aapne kabhi apne best friend ke bare mein kisi ko kuch negative bataya ho?", en: "Have you ever told someone something negative about your best friend?", category: "extreme" },
  { hi: "Kya kabhi aapne apne pyaar ki wajah se kisi aur ka dil todha ho?", en: "Have you ever broken someone's heart because of your own feelings for another person?", category: "extreme" },
  { hi: "Aapko lagta hai aap kisi ko genuinely bhool sakte ho ya nahi?", en: "Do you think you can genuinely forget someone or not?", category: "extreme" },
  { hi: "Kya aapne kabhi apne dost se competitive feel kiya ho unki achievements pe?", en: "Have you ever felt competitive with a friend over their achievements?", category: "extreme" },
  { hi: "Aapne kabhi kisi rishte mein doosre insaan ko less priority di ho jaan boojh kar?", en: "Have you ever intentionally given a partner less priority in a relationship?", category: "extreme" },
  { hi: "Kya aapko lagta hai aap kisi ke saath fake dosti nibha rahe ho abhi?", en: "Do you think you're currently maintaining a fake friendship with someone?", category: "extreme" },
  { hi: "Aapne kabhi kisi ki personal baat sabko bata di ho unki permission ke bina?", en: "Have you ever shared someone's personal matter with everyone without their permission?", category: "extreme" },
  { hi: "Is group mein sabse zyada aap kisse compete karte ho silently?", en: "Who in this group do you silently compete with the most?", category: "extreme" },
  { hi: "Kya aapne kabhi kisi ki success dekh ke unhe niche dikhane ki koshish ki ho?", en: "Have you ever tried to put someone down after seeing their success?", category: "extreme" },
  { hi: "Aapne kabhi kisi ka number block karke usse ignore kiya ho jaan boojh kar?", en: "Have you ever blocked someone's number to intentionally ignore them?", category: "extreme" },
  { hi: "Kya kabhi aapne kisi ki galti pe unse zyada khud se lie bola ho?", en: "Have you ever lied to yourself more than to someone about their mistake?", category: "extreme" },
  { hi: "Aapko sabse zyada dar kis baat ka hai apne future relationships ke bare mein?", en: "What scares you most about your future relationships?", category: "extreme" },
  { hi: "Kya aapne kabhi apne parents ko koi financial ya personal baat chhupayi ho?", en: "Have you ever hidden a financial or personal matter from your parents?", category: "extreme" },
  { hi: "Aapne kabhi kisi ko unki peeth peeche judge kiya ho unke lifestyle ko lekar?", en: "Have you ever judged someone behind their back about their lifestyle?", category: "extreme" },
  { hi: "Kya kabhi aapne apna asli opinion kisi se chhupaya ho sirf conflict avoid karne ke liye?", en: "Have you ever hidden your real opinion from someone just to avoid conflict?", category: "extreme" },
  { hi: "Is group mein aap kisko sabse zyada apna competitor maante ho, kisi bhi field mein?", en: "Who in this group do you consider your biggest competitor, in any field?", category: "extreme" },
  { hi: "Kya aapne kabhi kisi ki personal photo ya video kisi aur ko dikhayi ho bina unki permission ke?", en: "Have you ever shown someone else's personal photo or video without their permission?", category: "extreme" },
  { hi: "Aapko lagta hai aap kisi ke saath abhi bhi jhoot bol rahe ho? Kaunsi baat?", en: "Do you think you're still lying to someone right now? About what?", category: "extreme" },
  { hi: "Kya kabhi aapne apna dost badalne ki wajah se kisi purane dost ko replace kiya ho?", en: "Have you ever replaced an old friend after making a new one?", category: "extreme" },
  { hi: "Aapne kabhi kisi ko unki weakness ke baare mein taunt kiya ho?", en: "Have you ever taunted someone about their weakness?", category: "extreme" },
  { hi: "Kya aapko lagta hai aap kisi rishte mein 'settle' kar rahe the sirf akele na hone ke liye?", en: "Do you think you were 'settling' in a relationship just to avoid being alone?", category: "extreme" },
  { hi: "Aapne kabhi kisi ka break up karwaya ho apni baaton se, jaan boojh kar ya anjaane mein?", en: "Have you ever caused someone's breakup through your words, intentionally or unintentionally?", category: "extreme" },
  { hi: "Kya kabhi aapne khud ko justify karne ke liye jhoot pe jhoot bola ho?", en: "Have you ever told lie after lie just to justify yourself?", category: "extreme" },
  { hi: "Aapko sabse bada guilt kis cheez ka hai apne kisi close relationship mein?", en: "What's your biggest source of guilt in one of your close relationships?", category: "extreme" },
  { hi: "Kya kabhi aapne apne dost ko sach bolne se roka ho sirf apna fayda dekhke?", en: "Have you ever stopped a friend from telling the truth just for your own benefit?", category: "extreme" },
  { hi: "Aapne kabhi kisi crush/partner ko doosre se compare kiya ho unhe pata chale bina?", en: "Have you ever compared your crush/partner to someone else without them knowing?", category: "extreme" },
  { hi: "Is group mein sabse zyada aapko kaun manipulate karta hai lagta hai?", en: "Who in this group do you feel manipulates others the most?", category: "extreme" },
  { hi: "Kya kabhi aapne kisi rishte ko sirf jaldi khatam kiya kyunki wo mushkil ho raha tha?", en: "Have you ever ended a relationship early just because it was getting difficult?", category: "extreme" },
  { hi: "Aapne kabhi kisi ko emotionally use kiya ho apne fayde ke liye?", en: "Have you ever emotionally used someone for your own benefit?", category: "extreme" },
  { hi: "Kya aapko lagta hai aap kisi rishte mein dono taraf khel rahe ho abhi?", en: "Do you think you're playing both sides in a relationship right now?", category: "extreme" },
  { hi: "Aapne kabhi kisi dost ki kamzori ko unke against use kiya ho argument mein?", en: "Have you ever used a friend's weakness against them in an argument?", category: "extreme" },
  { hi: "Kya kabhi aapne apna asli intention chhupaya ho kisi rishte mein shuru mein?", en: "Have you ever hidden your real intentions at the start of a relationship?", category: "extreme" },
  { hi: "Aapko sabse zyada regret kisi ke saath ki gayi behavior ka hai kya?", en: "Do you regret the way you behaved with someone the most?", category: "extreme" },
  { hi: "Kya kabhi aapne apna crush kisi close friend se chhupaya ho unke reaction ke dar se?", en: "Have you ever hidden a crush from a close friend out of fear of their reaction?", category: "extreme" },
  { hi: "Aapne kabhi kisi ki privacy invade ki ho unki jaankari ke bina?", en: "Have you ever invaded someone's privacy without their knowledge?", category: "extreme" },
  { hi: "Is group mein aap kisse most competitive feel karte ho apni looks/achievements ko lekar?", en: "Who in this group do you feel most competitive with regarding looks/achievements?", category: "extreme" },
  { hi: "Kya kabhi aapne apna best friend badla ho kisi galatfehmi ki wajah se jo clear nahi hui?", en: "Have you ever changed your best friend due to a misunderstanding that was never cleared up?", category: "extreme" },
  { hi: "Aapne kabhi kisi rishte mein khud ko victim dikhaya ho jab galti aapki thi?", en: "Have you ever portrayed yourself as the victim in a relationship when the mistake was yours?", category: "extreme" },
  { hi: "Kya aapko lagta hai aapne kisi ko sirf convenience ke liye apne pass rakha hai?", en: "Do you think you've kept someone around just for convenience?", category: "extreme" },
  { hi: "Aapne kabhi kisi ki insecurity ka mazak banaya ho unhe pata chale bina?", en: "Have you ever mocked someone's insecurity without them knowing?", category: "extreme" },
  { hi: "Kya kabhi aapne kisi ko unfairly punish kiya ho apna gussa nikaalne ke liye?", en: "Have you ever unfairly punished someone just to vent your anger?", category: "extreme" },
  { hi: "Aapko lagta hai aap kisi rishtey mein doosre insaan se zyada khud ko priority dete ho?", en: "Do you think you prioritize yourself more than the other person in a relationship?", category: "extreme" },
  { hi: "Kya kabhi aapne apna crush ya partner kisi se secretly compare karke rakha ho decision lene ke liye?", en: "Have you ever secretly kept comparing your crush/partner to someone else while deciding?", category: "extreme" },
  { hi: "Aapne kabhi kisi close dost ka support na kiya ho jab unhe zaroorat thi?", en: "Have you ever failed to support a close friend when they needed it?", category: "extreme" },
  { hi: "Is group mein sabse zyada kaun apni image ke liye jhoot bolta lagta hai aapko?", en: "Who in this group seems to lie the most for their image?", category: "extreme" },
  { hi: "Kya kabhi aapne kisi ki genuine feeling ko fake bola ho unke saamne?", en: "Have you ever called someone's genuine feeling fake to their face?", category: "extreme" },
  { hi: "Aapne kabhi kisi ke sath rehte hue kisi aur ke bare mein socha ho romantically?", en: "Have you ever thought about someone else romantically while being with a partner?", category: "extreme" },
  { hi: "Kya aapko lagta hai aap kisi rishte mein control karne ki tendency rakhte ho?", en: "Do you think you have a tendency to control in a relationship?", category: "extreme" },
  { hi: "Aapne kabhi apni galti kisi aur pe daali ho sirf face save karne ke liye?", en: "Have you ever blamed your mistake on someone else just to save face?", category: "extreme" },
  { hi: "Kya kabhi aapne kisi rishte mein sach bolne se zyada convenient jhoot chuna ho?", en: "Have you ever chosen a convenient lie over the truth in a relationship?", category: "extreme" },
  { hi: "Aapko lagta hai aap kisi ki jagah aasani se le sakte ho unki feelings soche bina?", en: "Do you think you could easily take someone's place without considering their feelings?", category: "extreme" },
  { hi: "Kya kabhi aapne kisi dost ke pyaar mein pad ke unse dosti kharab ki ho?", en: "Have you ever ruined a friendship because you fell for a friend romantically?", category: "extreme" },
  { hi: "Aapne kabhi kisi ki weakness ko unke saamne highlight kiya ho argument jeetne ke liye?", en: "Have you ever highlighted someone's weakness to their face just to win an argument?", category: "extreme" },
  { hi: "Kya aapko lagta hai aapki koi ek personality trait rishtey todne ki wajah ban sakti hai?", en: "Do you think one of your personality traits could be a reason relationships break?", category: "extreme" },
  { hi: "Aapne kabhi kisi ko dhoka diya ho jo aapko full trust karta tha?", en: "Have you ever deceived someone who fully trusted you?", category: "extreme" },
  { hi: "Is group mein sabse zyada aap kisse apni asli feelings chhupate ho?", en: "Who in this group do you hide your real feelings from the most?", category: "extreme" },
  { hi: "Kya kabhi aapne kisi ka favour maang ke wapas thank you bhi nahi bola ho?", en: "Have you ever asked someone for a favor and not even thanked them back?", category: "extreme" },
  { hi: "Aapne kabhi kisi ki family/friends ko unke against turn karne ki koshish ki ho?", en: "Have you ever tried to turn someone's family/friends against them?", category: "extreme" },
  { hi: "Kya aapko lagta hai aap apni galtiyon ko accept karne se bachte ho?", en: "Do you think you avoid accepting your own mistakes?", category: "extreme" },
  { hi: "Aapne kabhi kisi rishtey mein doosre insaan ko emotionally blackmail kiya ho?", en: "Have you ever emotionally blackmailed someone in a relationship?", category: "extreme" },
  { hi: "Kya kabhi aapne apna past kisi naye rishtey mein chhupaya ho?", en: "Have you ever hidden your past from a new relationship?", category: "extreme" },
  { hi: "Aapko lagta hai aapne kisi ke saath sabse zyada unfair behavior kab ki thi?", en: "When do you think you behaved most unfairly with someone?", category: "extreme" },
  { hi: "Kya kabhi aapne kisi ko apni zindagi se sirf isliye nikala kyunki wo aapke fayde mein nahi tha?", en: "Have you ever cut someone out of your life just because they weren't beneficial to you?", category: "extreme" },
  { hi: "Aapne kabhi khud ko better dikhane ke liye kisi ki burai ki ho?", en: "Have you ever spoken badly of someone just to make yourself look better?", category: "extreme" },
  { hi: "Is group mein sabse zyada aap kisko underestimate karte ho?", en: "Who in this group do you underestimate the most?", category: "extreme" },

];

const dareQuestions = [
  // ---------- MILD ----------
  { hi: "Ek glass paani mein ek chammach namak daalke piyo", en: "Drink a glass of water with one spoon of salt mixed in", category: "mild" },
  { hi: "Robot ki tarah chalke pura kamra ek chakkar lagao", en: "Walk around the room once like a robot", category: "mild" },
  { hi: "5 jumping jacks karo gaana gaate hue", en: "Do 5 jumping jacks while singing a song", category: "mild" },
  { hi: "Apni awaaz ko cartoon character jaisi banake agla round khelo", en: "Play the next round talking in a cartoon character voice", category: "mild" },

    { hi: "10 second tak apni pasandida animal ki awaaz nikalo", en: "Make the sound of your favorite animal for 10 seconds", category: "mild" },
  { hi: "Apne haath se ek chhota heart banake camera ke saamne dikhao", en: "Make a small heart with your hands and show it to the camera", category: "mild" },
  { hi: "Ek filmy dialogue bolo dramatic style mein", en: "Say a filmy dialogue in a dramatic style", category: "mild" },
  { hi: "30 second tak ek pair pe khade raho", en: "Stand on one leg for 30 seconds", category: "mild" },
  { hi: "Apni favourite movie ka ek scene act karke dikhao (bina bataye kaunsi hai)", en: "Act out a scene from your favorite movie without saying which one it is", category: "mild" },
  { hi: "Ek tongue twister 3 baar jaldi jaldi bolo", en: "Say a tongue twister 3 times quickly", category: "mild" },
  { hi: "Apni awaaz ko baby jaisi banake agla sentence bolo", en: "Say your next sentence in a baby voice", category: "mild" },
  { hi: "5 second mein apne chehre pe 3 alag expressions dikhao", en: "Show 3 different facial expressions in 5 seconds", category: "mild" },
  { hi: "Ek chhota sa dance step sikhao group ko", en: "Teach the group a small dance step", category: "mild" },
  { hi: "Apna naam ulta (backwards) bolne ki koshish karo", en: "Try to say your name backwards", category: "mild" },
  { hi: "Kisi bhi ek cheez ko lekar 15 second ka ad banao", en: "Make up a 15-second ad for any random object nearby", category: "mild" },
  { hi: "Group ke ek member ki nakal (mimic) karo 10 second ke liye", en: "Mimic one group member's mannerisms for 10 seconds", category: "mild" },
  { hi: "Ek push-up karo", en: "Do one push-up", category: "mild" },
  { hi: "Apni palm pe ek chhota drawing banao marker/pen se", en: "Draw a small doodle on your palm with a pen/marker", category: "mild" },
  { hi: "Bina hasse 20 second tak seedha kisi ko dekho", en: "Look straight at someone for 20 seconds without laughing", category: "mild" },
  { hi: "Apni favourite cartoon character ki awaaz nikalo", en: "Do the voice of your favorite cartoon character", category: "mild" },
  { hi: "Ek chhota sa freestyle rap banao apne naam pe", en: "Make up a short freestyle rap about your own name", category: "mild" },
  { hi: "Kisi bhi gaane ki ek line opera style mein gao", en: "Sing one line of any song in an opera style", category: "mild" },
  { hi: "10 second tak robot ki tarah baat karo", en: "Talk like a robot for 10 seconds", category: "mild" },
  { hi: "Apna favourite pose ek photo ke liye dikhao", en: "Show your favorite pose for a photo", category: "mild" },
  { hi: "Ek chhoti si joke sunao group ko", en: "Tell a short joke to the group", category: "mild" },
  { hi: "Apne haath se shadow puppet banake dikhao", en: "Make a shadow puppet with your hands and show it", category: "mild" },
  { hi: "5 baar jump karo apna favourite gaana gaate hue", en: "Jump 5 times while singing your favorite song", category: "mild" },
  { hi: "Apni aankhen band karke 10 second tak khada raho", en: "Stand still with your eyes closed for 10 seconds", category: "mild" },
  { hi: "Group ke kisi member ko genuine compliment do", en: "Give a genuine compliment to a group member", category: "mild" },
  { hi: "Apna favourite dialogue kisi villain style mein bolo", en: "Say your favorite line in a villain's style", category: "mild" },
  { hi: "Ek minute tak sirf haath se signal karke baat karo", en: "Communicate using only hand signals for one minute", category: "mild" },
  { hi: "Apna naam ek gaane ki tune mein gao", en: "Sing your own name to a song's tune", category: "mild" },
  { hi: "Kisi bhi cheez ko balance karo apne sar pe 10 second ke liye", en: "Balance any object on your head for 10 seconds", category: "mild" },
  { hi: "Apni favourite superhero pose dikhao", en: "Show your favorite superhero pose", category: "mild" },
  { hi: "Ek chhota beatbox try karo 10 second ke liye", en: "Try beatboxing for 10 seconds", category: "mild" },
  { hi: "Apni awaaz badalke ek news anchor ki tarah headline bolo", en: "Change your voice and announce a headline like a news anchor", category: "mild" },
  { hi: "Group photo ke liye sabse funny face banao", en: "Make the funniest face for a group photo", category: "mild" },
  { hi: "Apna favourite dance move 10 second tak karo bina gaane ke", en: "Do your favorite dance move for 10 seconds without music", category: "mild" },
  { hi: "Ek chhoti si kahani banao 20 second mein kisi random cheez pe", en: "Make up a short story in 20 seconds about any random object", category: "mild" },
  { hi: "Apne haath se ek origami (kagaz ka) shape banane ki koshish karo", en: "Try to make an origami paper shape with your hands", category: "mild" },
  { hi: "10 second tak sirf smile karo bina bole", en: "Just smile for 10 seconds without speaking", category: "mild" },
  { hi: "Apni favourite catchphrase 3 alag emotions ke saath bolo", en: "Say your favorite catchphrase with 3 different emotions", category: "mild" },
  { hi: "Group ke kisi member ka naam ek gaane mein fit karke gao", en: "Fit a group member's name into a song and sing it", category: "mild" },
  { hi: "Apne kamre mein jaake koi ek ajeeb cheez laao aur dikhao", en: "Go to your room and bring back one weird object to show", category: "mild" },
  { hi: "Ek minute tak bina blink kiye camera ko dekho", en: "Stare at the camera without blinking for one minute", category: "mild" },
  { hi: "Apna favourite movie dialogue kisi comedy style mein bolo", en: "Say your favorite movie dialogue in a comedic style", category: "mild" },
  { hi: "10 jumping jacks fast speed mein karo", en: "Do 10 jumping jacks at fast speed", category: "mild" },
  { hi: "Apna favourite emoji face expression se dikhao", en: "Show your favorite emoji using your face expression", category: "mild" },
  { hi: "Ek chhota dialogue kisi accent mein bolo (jo bhi aata ho)", en: "Say a short line in any accent you can do", category: "mild" },
  { hi: "Apni kursi/sofa pe khade hoke ek pose do 5 second ke liye", en: "Stand on your chair/sofa and pose for 5 seconds", category: "mild" },
  { hi: "Group ko apna favourite handshake sikhao (bana lo agar nahi hai)", en: "Teach the group your favorite handshake (make one up if you don't have one)", category: "mild" },
  { hi: "Apna naam sign language mein spell karne ki koshish karo", en: "Try spelling your name in sign language", category: "mild" },
  { hi: "10 second tak apni favourite jagah ka description do bina naam liye", en: "Describe your favorite place for 10 seconds without naming it", category: "mild" },
  { hi: "Apni pasandida movie ka poster pose recreate karo", en: "Recreate the pose from your favorite movie's poster", category: "mild" },
  { hi: "Ek line kisi rap song ki fast bolo", en: "Say one line from a rap song fast", category: "mild" },
  { hi: "Apna favourite snack khane ka acting karo bina snack ke", en: "Act out eating your favorite snack without actually having it", category: "mild" },
  { hi: "5 second tak apne favourite animal ki chaal chalo", en: "Walk like your favorite animal for 5 seconds", category: "mild" },
  { hi: "Group ke saamne apna favourite quote bolo confidently", en: "Say your favorite quote confidently in front of the group", category: "mild" },
  { hi: "Apna phone ka wallpaper dikhao group ko", en: "Show your phone wallpaper to the group", category: "mild" },
  { hi: "10 second tak apne favourite superhero ki flying pose do", en: "Do your favorite superhero's flying pose for 10 seconds", category: "mild" },
  { hi: "Ek chhota poem banao apne naam pe", en: "Make up a short poem about your own name", category: "mild" },
  { hi: "Apni favourite emoji ki tarah face expression banao aur 5 second hold karo", en: "Make a face expression like your favorite emoji and hold it for 5 seconds", category: "mild" },
  { hi: "Group ko apna favourite childhood game ka naam bolke rules batao", en: "Tell the group your favorite childhood game and explain its rules", category: "mild" },
  { hi: "Apni favourite movie ka music/theme hum karo 10 second", en: "Hum your favorite movie's music/theme for 10 seconds", category: "mild" },
  { hi: "10 second tak apne favourite sport ki acting karo", en: "Act out your favorite sport for 10 seconds", category: "mild" },
  { hi: "Apna favourite dialogue kisi kid ki awaaz mein bolo", en: "Say your favorite dialogue in a kid's voice", category: "mild" },
  { hi: "Group ke saamne apni favourite pose 3 baar repeat karo", en: "Repeat your favorite pose 3 times in front of the group", category: "mild" },
  { hi: "Ek chhoti si dua/wish bolo group ke liye", en: "Say a short wish/blessing for the group", category: "mild" },
  { hi: "Apna favourite gaana bina music ke a capella gao 10 second", en: "Sing your favorite song a capella for 10 seconds without music", category: "mild" },
  { hi: "Group ke kisi member ko apna favourite meme describe karo", en: "Describe your favorite meme to a group member", category: "mild" },
  { hi: "10 second tak apni favourite comfort activity ki acting karo", en: "Act out your favorite comfort activity for 10 seconds", category: "mild" },
  { hi: "Apna favourite ice cream flavour ka taste describe karo dramatically", en: "Describe the taste of your favorite ice cream flavor dramatically", category: "mild" },
  { hi: "Group ko batao apni favourite emoji combo aur wo kyun use karte ho", en: "Tell the group your favorite emoji combo and why you use it", category: "mild" },
  { hi: "5 second tak apne favourite cartoon ki walking style dikhao", en: "Show your favorite cartoon's walking style for 5 seconds", category: "mild" },
  { hi: "Apna favourite subject teach karne ki acting karo 15 second", en: "Act out teaching your favorite subject for 15 seconds", category: "mild" },
  { hi: "Group ke saamne apna favourite pose kisi statue jaisa freeze karo 10 second", en: "Freeze in your favorite pose like a statue for 10 seconds", category: "mild" },
  { hi: "Apni favourite movie ka trailer voice mein 2 line bolo", en: "Say 2 lines in a movie trailer voice about your favorite film", category: "mild" },
  { hi: "10 second tak apna favourite weather act karke dikhao", en: "Act out your favorite weather for 10 seconds", category: "mild" },
  { hi: "Group ko apna favourite childhood cartoon ka theme song hum karo", en: "Hum your favorite childhood cartoon's theme song to the group", category: "mild" },
  { hi: "Apna favourite dance move ek chair pe baithe baithe karo", en: "Do your favorite dance move while sitting in a chair", category: "mild" },
  { hi: "5 second tak apne favourite superhero ki pose freeze karo", en: "Freeze in your favorite superhero's pose for 5 seconds", category: "mild" },
  { hi: "Group ke saamne apni favourite joke ka punchline dramatically bolo", en: "Say the punchline of your favorite joke dramatically", category: "mild" },
  { hi: "Apna favourite outfit describe karo jaise fashion show mein ho", en: "Describe your favorite outfit like you're on a fashion show", category: "mild" },
  { hi: "10 second tak apna favourite hobby mime (acting) karke dikhao", en: "Mime your favorite hobby for 10 seconds", category: "mild" },
  { hi: "Group ko apna favourite travel destination describe karo bina naam liye", en: "Describe your favorite travel destination without naming it", category: "mild" },
  { hi: "Apna favourite gaana ek slow motion mein lip sync karo", en: "Lip sync your favorite song in slow motion", category: "mild" },
  { hi: "5 second tak apne favourite emoji ki body pose banao", en: "Make a body pose of your favorite emoji for 5 seconds", category: "mild" },
  { hi: "Group ke saamne apna favourite childhood snack khaane ka acting karo", en: "Act out eating your favorite childhood snack in front of the group", category: "mild" },
  { hi: "Apna favourite sport commentator ki tarah 10 second commentary karo", en: "Do sports commentary like your favorite commentator for 10 seconds", category: "mild" },
  { hi: "10 second tak apne favourite gaane pe silent dance karo (bina music)", en: "Silently dance to your favorite song for 10 seconds (no music)", category: "mild" },
  { hi: "Group ko apna favourite quote 3 alag voices mein bolke sunao", en: "Say your favorite quote in 3 different voices for the group", category: "mild" },
  { hi: "Apna favourite subject ka ek fun fact batao group ko", en: "Tell the group a fun fact about your favorite subject", category: "mild" },
  { hi: "5 second tak apni favourite animal ki tarah stretch karo", en: "Stretch like your favorite animal for 5 seconds", category: "mild" },
  { hi: "Group ke saamne apna favourite childhood memory ek minute mein sunao", en: "Tell your favorite childhood memory to the group in one minute", category: "mild" },
  { hi: "Apna favourite dialogue reverse order mein bolne ki koshish karo", en: "Try saying your favorite dialogue in reverse word order", category: "mild" },
  { hi: "10 second tak apne favourite instrument bajane ki acting karo", en: "Act out playing your favorite instrument for 10 seconds", category: "mild" },
  { hi: "Group ko apna favourite pose photoshoot style mein dikhao", en: "Show your favorite pose in a photoshoot style", category: "mild" },
  { hi: "Apna favourite gaana whistle karke gao 10 second", en: "Whistle your favorite song for 10 seconds", category: "mild" },
  { hi: "5 second tak apne favourite mausam mein hone ka reaction do", en: "Give a reaction as if you're in your favorite weather for 5 seconds", category: "mild" },
  { hi: "Group ke saamne apna favourite childhood game khelne ki acting karo", en: "Act out playing your favorite childhood game in front of the group", category: "mild" },
  { hi: "Apna favourite dialogue ek statue ban ke bolo (bina hile)", en: "Say your favorite dialogue while standing frozen like a statue", category: "mild" },
  { hi: "10 second tak apne favourite fictional character ki walking style dikhao", en: "Show your favorite fictional character's walking style for 10 seconds", category: "mild" },
  { hi: "Group ko apna favourite emoji story 3 emojis se sunao", en: "Tell the group a story using only 3 emojis representing your favorites", category: "mild" },

// ---------- SPICY ----------
  { hi: "Apne crush ka naam zor se chillao (agar crush nahi hai to apne pyaar ka naam bana lo)", en: "Shout out your crush's name loudly (if you don't have one, make one up)", category: "spicy" },
  { hi: "Apne parents ko voice message bhejo 'I love you' bolke, bina wajah", en: "Send your parents a voice message saying 'I love you' for no reason", category: "spicy" },
  { hi: "Kisi random contact ko call karke 'Happy Birthday' bolo aur turant kaato", en: "Call a random contact, say 'Happy Birthday' and hang up immediately", category: "spicy" },
  { hi: "Apna coffee/chai order kisi filmy style mein 'act' karke batao", en: "Order your coffee/tea in a dramatic filmy acting style", category: "spicy" },

    { hi: "Apne crush ko ek innocent sa compliment message bhejo abhi", en: "Send your crush an innocent compliment message right now", category: "spicy" },
  { hi: "Group ke kisi member ka contact save karo funny nickname ke saath", en: "Save a group member's contact with a funny nickname", category: "spicy" },
  { hi: "Apne last 5 Instagram likes dikhao group ko", en: "Show the group your last 5 Instagram likes", category: "spicy" },
  { hi: "Ek voice note bhejo apne crush ko 'hi' bolke, bina explain kiye", en: "Send your crush a voice note just saying 'hi' without explanation", category: "spicy" },
  { hi: "Apne phone ka 'most used contact' dikhao group ko", en: "Show the group your 'most contacted person' on your phone", category: "spicy" },
  { hi: "Kisi ex ya crush ko ek purana photo memory share karo (agar comfortable ho)", en: "Share an old photo memory with an ex or crush (if comfortable)", category: "spicy" },
  { hi: "Apni playlist ka last saved romantic gaana group ko sunao", en: "Play the last romantic song you saved in your playlist for the group", category: "spicy" },
  { hi: "Group ke kisi member ko unki ek achhi quality batao seedhe aankhon mein dekh ke", en: "Tell a group member one good quality about them while looking them in the eye", category: "spicy" },
  { hi: "Apne crush ki last story pe ek genuine reaction bhejo abhi", en: "Send a genuine reaction to your crush's last story right now", category: "spicy" },
  { hi: "Group ko batao aapka last 'situationship' kiske saath tha (agar comfortable ho)", en: "Tell the group who your last 'situationship' was with (if comfortable)", category: "spicy" },
  { hi: "Apne phone gallery ka ek random photo bina dekhe group ko dikhao", en: "Show the group a random photo from your gallery without checking it first", category: "spicy" },
  { hi: "Kisi crush ya interest ko ek chhota compliment call karke do", en: "Call a crush or interest and give them a small compliment", category: "spicy" },
  { hi: "Apna Instagram bio zor se padho group ko", en: "Read your Instagram bio out loud to the group", category: "spicy" },
  { hi: "Group ke kisi member ke saath eye contact 15 second tak bina hasse maintain karo", en: "Maintain eye contact with a group member for 15 seconds without laughing", category: "spicy" },
  { hi: "Apne crush ke naam se ek chhota poem banao aur sunao", en: "Make up a short poem using your crush's name and recite it", category: "spicy" },
  { hi: "Apna last search history ka ek word (jo bhi comfortable ho) group ko batao", en: "Tell the group one word from your last search history that you're comfortable sharing", category: "spicy" },
  { hi: "Apne crush ko ek gaana suggest karo message karke", en: "Suggest a song to your crush via message", category: "spicy" },
  { hi: "Group ke saamne apna 'type' describe karo detail mein", en: "Describe your 'type' in detail to the group", category: "spicy" },
  { hi: "Apne phone ka last received compliment message padho group ko", en: "Read out the last compliment message you received on your phone", category: "spicy" },
  { hi: "Ek flirty pickup line try karo group ke kisi member pe (funny tone mein)", en: "Try a flirty pickup line on a group member (in a funny tone)", category: "spicy" },
  { hi: "Apne crush ki koi ek achhi quality group ko batao", en: "Tell the group one good quality about your crush", category: "spicy" },
  { hi: "Apna last DM conversation ka topic (bina naam liye) group ko batao", en: "Tell the group the topic of your last DM conversation (without naming who)", category: "spicy" },
  { hi: "Group ko apna 'dream date' describe karo detail mein", en: "Describe your 'dream date' in detail to the group", category: "spicy" },
  { hi: "Apne crush ko ek emoji bhejo abhi bina kuch bole", en: "Send your crush a single emoji right now without saying anything", category: "spicy" },
  { hi: "Group ke kisi member ko ek genuine 'why I like talking to you' bolo", en: "Tell a group member one genuine reason why you like talking to them", category: "spicy" },
  { hi: "Apna last liked photo Instagram pe group ko dikhao", en: "Show the group the last photo you liked on Instagram", category: "spicy" },
  { hi: "Ek romantic dialogue kisi movie se bolo dramatically", en: "Say a romantic dialogue from a movie dramatically", category: "spicy" },
  { hi: "Group ko batao aapki 'red flag' kya hai relationship mein", en: "Tell the group what your 'red flag' is in a relationship", category: "spicy" },
  { hi: "Apne crush ke saath last conversation ka mood describe karo", en: "Describe the mood of your last conversation with your crush", category: "spicy" },
  { hi: "Group ke saamne apna 'green flag' quality batao", en: "Tell the group your 'green flag' quality", category: "spicy" },
  { hi: "Apna phone kisi ko do 10 second ke liye unki choice ka ek app dikhane", en: "Hand your phone to someone for 10 seconds to show any app of their choice", category: "spicy" },
  { hi: "Group ko batao kisne aapko last baar 'cute' bola tha", en: "Tell the group who last called you 'cute'", category: "spicy" },
  { hi: "Apne crush ko compliment karte hue ek voice message record karo (bhejo mat, bas record karo)", en: "Record a voice message complimenting your crush (don't send it, just record it)", category: "spicy" },
  { hi: "Group ke kisi member se pucho unka 'type' kya hai", en: "Ask a group member what their 'type' is", category: "spicy" },
  { hi: "Apna last sent 'good morning/good night' text kisko tha, batao", en: "Tell the group who your last 'good morning/good night' text was to", category: "spicy" },
  { hi: "Ek dialogue bolo jaise aap kisi ko propose kar rahe ho (funny tone mein)", en: "Say a line as if you're proposing to someone (in a funny tone)", category: "spicy" },
  { hi: "Group ko batao aapka 'situationship' ka definition kya hai", en: "Tell the group your definition of a 'situationship'", category: "spicy" },
  { hi: "Apna last saved reel/video jo aapko romantic laga, group ko dikhao", en: "Show the group the last reel/video you saved that felt romantic", category: "spicy" },
  { hi: "Group ke kisi member ko ek 'would you rather' romantic question pucho", en: "Ask a group member a romantic 'would you rather' question", category: "spicy" },
  { hi: "Apna last crush kaun tha, sirf initial batao", en: "Tell the group just the initial of your last crush's name", category: "spicy" },
  { hi: "Ek slow romantic song ki line hum karo group ke saamne", en: "Hum a line from a slow romantic song in front of the group", category: "spicy" },
  { hi: "Group ko batao aapke liye 'perfect date' kaisa hoga", en: "Tell the group what your 'perfect date' would look like", category: "spicy" },
  { hi: "Apne crush ki tarah ek text likho (bhejo mat, bas dikhao group ko)", en: "Write a text as if messaging your crush (don't send, just show the group)", category: "spicy" },
  { hi: "Group ke kisi member ko unki smile ke bare mein compliment do", en: "Compliment a group member on their smile", category: "spicy" },
  { hi: "Apna last liked comment (kisi bhi post pe) group ko dikhao", en: "Show the group the last comment you liked on any post", category: "spicy" },
  { hi: "Ek chhota 'confession' bolo jo aapne kabhi kisi ko nahi bataya (halka wala)", en: "Say a small 'confession' you've never told anyone (a light one)", category: "spicy" },
  { hi: "Group ko batao aapko kis type ki texting style pasand hai", en: "Tell the group what texting style you find attractive", category: "spicy" },
  { hi: "Apne crush ke naam ka pehla letter zor se bolo", en: "Say the first letter of your crush's name out loud", category: "spicy" },
  { hi: "Group ke saamne acting karo jaise aap kisi date pe nervous ho", en: "Act out being nervous as if on a date, in front of the group", category: "spicy" },
  { hi: "Apna last sent voice message (koi bhi) group ko sunao", en: "Play your last sent voice message (any one) for the group", category: "spicy" },
  { hi: "Group ko batao aapko last baar kisne 'I miss you' bola tha", en: "Tell the group who last told you 'I miss you'", category: "spicy" },
  { hi: "Ek romantic movie scene 10 second ke liye act karke dikhao", en: "Act out a romantic movie scene for 10 seconds", category: "spicy" },
  { hi: "Group ke kisi member ko unki eyes/smile ke bare mein genuine compliment do", en: "Give a group member a genuine compliment about their eyes/smile", category: "spicy" },
  { hi: "Apna phone kisi ko do unki choice ka ek chat khol ke dikhane (comfortable ho to)", en: "Hand your phone to someone to open a chat of their choice (if comfortable)", category: "spicy" },
  { hi: "Group ko batao aapka 'crush criteria' kya hai", en: "Tell the group your 'crush criteria'", category: "spicy" },
  { hi: "Ek flirty compliment do group ke kisi member ko funny tone mein", en: "Give a flirty compliment to a group member in a funny tone", category: "spicy" },
  { hi: "Apne crush ko unfollow-follow karke dikhao (agar comfortable ho)", en: "Unfollow and refollow your crush on social media (if comfortable)", category: "spicy" },
  { hi: "Group ko batao aapko sabse zyada attractive body language kya lagti hai", en: "Tell the group what body language you find most attractive", category: "spicy" },
  { hi: "Apna last message jo aapne kisi crush ko bheja tha, describe karo (bina naam liye)", en: "Describe the last message you sent to a crush (without naming them)", category: "spicy" },
  { hi: "Group ke kisi member ke saath 10 second slow dance karo (funny style mein)", en: "Do a 10-second slow dance with a group member (in a funny style)", category: "spicy" },
  { hi: "Apna 'ideal partner' describe karo ek minute mein", en: "Describe your 'ideal partner' in one minute", category: "spicy" },
  { hi: "Group ko batao aapki last jealousy feeling kis wajah se hui thi", en: "Tell the group what caused your last feeling of jealousy", category: "spicy" },
  { hi: "Ek romantic dialogue apne crush ke liye likho aur zor se padho (bina bhejje)", en: "Write a romantic line for your crush and read it out loud (without sending)", category: "spicy" },
  { hi: "Group ke kisi member ko unke best quality ke liye ek hug do (agar comfortable ho)", en: "Give a group member a hug for their best quality (if comfortable)", category: "spicy" },
  { hi: "Apna crush ka photo (agar hai) 5 second ke liye group ko dikhao", en: "Show the group a photo of your crush for 5 seconds (if you have one)", category: "spicy" },
  { hi: "Group ko batao aapka 'ideal first date' location kya hoga", en: "Tell the group what your ideal first date location would be", category: "spicy" },
  { hi: "Apna last flirty text (agar hai) group ko padho bina naam liye", en: "Read your last flirty text to the group without revealing who it was to", category: "spicy" },
  { hi: "Group ke kisi member se pucho unhe kaisi date pasand hai", en: "Ask a group member what kind of date they'd enjoy", category: "spicy" },
  { hi: "Ek chhota compliment likho apne crush ke liye card pe (bina bhejje)", en: "Write a small compliment for your crush on paper (without sending it)", category: "spicy" },
  { hi: "Group ko batao aapko last baar kisne blush karaya tha", en: "Tell the group who last made you blush", category: "spicy" },
  { hi: "Apna phone lock karke kisi ko dedo 5 second ke liye without checking", en: "Lock your phone and hand it to someone for 5 seconds without checking it first", category: "spicy" },
  { hi: "Group ke saamne apna 'ideal proposal' describe karo", en: "Describe your 'ideal proposal' to the group", category: "spicy" },
  { hi: "Ek gaana bajao jo aapko apne crush ki yaad dilata hai", en: "Play a song that reminds you of your crush", category: "spicy" },
  { hi: "Group ko batao aapka 'love language' kya hai", en: "Tell the group what your 'love language' is", category: "spicy" },
  { hi: "Apna last message jo unread pada hai kisi crush ka, mention karo (bina detail ke)", en: "Mention if there's an unread message from a crush sitting in your inbox (no details needed)", category: "spicy" },
  { hi: "Group ke kisi member ko ek honest opinion do unki dating life ke bare mein", en: "Give a group member an honest opinion about their dating life", category: "spicy" },
  { hi: "Apna crush wala emoji (jo unke liye use karte ho) group ko batao", en: "Tell the group the emoji you use for your crush", category: "spicy" },
  { hi: "Group ko batao aapka 'biggest romantic regret' kya hai", en: "Tell the group your 'biggest romantic regret'", category: "spicy" },
  { hi: "Ek chhota gift idea batao jo aap apne crush ko dena chahoge", en: "Suggest a small gift idea you'd want to give your crush", category: "spicy" },
  { hi: "Group ke kisi member ko unki dressing sense ke liye compliment do", en: "Compliment a group member on their dressing sense", category: "spicy" },
  { hi: "Apna last flirty reply (agar hai) group ko describe karo", en: "Describe your last flirty reply to the group", category: "spicy" },
  { hi: "Group ko batao aapko kaunsi date activity sabse zyada exciting lagti hai", en: "Tell the group which date activity excites you the most", category: "spicy" },
  { hi: "Apne crush ki last profile picture describe karo bina naam liye", en: "Describe your crush's latest profile picture without naming them", category: "spicy" },
  { hi: "Group ke saamne apna 'ideal anniversary' plan batao", en: "Tell the group your ideal anniversary plan", category: "spicy" },
  { hi: "Ek chhoti si love story banao 30 second mein kisi random do naamon se", en: "Make up a short 30-second love story using two random names", category: "spicy" },
  { hi: "Group ko batao aapka crush aapse kya nahi jaanta", en: "Tell the group something your crush doesn't know about you", category: "spicy" },
  { hi: "Apna last message jo aapne relationship ke bare mein kisi ko bheja, describe karo", en: "Describe the last message you sent someone about relationships", category: "spicy" },
  { hi: "Group ke kisi member ko unke confidence ke liye compliment do", en: "Compliment a group member on their confidence", category: "spicy" },
  { hi: "Apna 'if I had a crush right now' answer batao group ko", en: "Tell the group your answer to 'if I had a crush right now, it would be...'", category: "spicy" },
  { hi: "Group ko batao aapko kaunsa gesture sabse zyada romantic lagta hai", en: "Tell the group what gesture feels most romantic to you", category: "spicy" },
  { hi: "Ek chhota 'what if' scenario batao apne crush ke saath (funny wala)", en: "Share a funny 'what if' scenario involving your crush", category: "spicy" },
  { hi: "Group ke kisi member se pucho unka 'dream partner trait' kya hai", en: "Ask a group member what their 'dream partner trait' is", category: "spicy" },
  { hi: "Apna last 'accidental like' (kisi purani photo pe) group ko batao", en: "Tell the group about your last 'accidental like' on an old photo", category: "spicy" },
  { hi: "Group ko batao aapko sabse zyada kaunsi compliment sunna pasand hai", en: "Tell the group what compliment you love hearing the most", category: "spicy" },
  { hi: "Ek chhota sa 'crush confession' likho anonymous style mein aur group ko padho", en: "Write a short anonymous-style 'crush confession' and read it to the group", category: "spicy" },
  { hi: "Group ke kisi member ko batao unke saath baat karke kaisa lagta hai", en: "Tell a group member how it feels to talk to them", category: "spicy" },
  { hi: "Apna last 'butterflies' wala moment describe karo group ko", en: "Describe your last moment that gave you 'butterflies'", category: "spicy" },

// ---------- EXTREME ----------
  { hi: "Bahar jaake kisi bhi ghar ki bell bajao aur bina bataye bhaag aao", en: "Go outside, ring any house's doorbell and run away without saying anything", category: "extreme" },
  { hi: "Apni last WhatsApp chat ka ek message zor se padho (jo bhi ho)", en: "Read out loud one message from your last WhatsApp chat, whatever it is", category: "extreme" },
  { hi: "Apne phone ka last photo bina explain kiye group ko dikhao", en: "Show the group your last phone photo without explaining it", category: "extreme" },
  { hi: "Apne phone ke last 3 emoji searches dikhao group ko", en: "Show the group your last 3 emoji searches", category: "extreme" },
  { hi: "Apne last 3 chats (kisi bhi platform pe) group ko dikhao (agar comfortable ho)", en: "Show the group your last 3 chats on any platform (if comfortable)", category: "extreme" },
  { hi: "Group ke kisi member ko unki ek genuine weakness batao jo aapko lagti hai", en: "Tell a group member one genuine weakness of theirs that you've noticed", category: "extreme" },
  { hi: "Apne phone se ek random contact ko call karo aur pucho 'sab thik hai?'", en: "Call a random contact from your phone and ask 'is everything okay?'", category: "extreme" },
  { hi: "Group ko batao aapka phone ka lock pattern/password ka pehla digit", en: "Tell the group the first digit of your phone's lock password/pattern", category: "extreme" },
  { hi: "Apna last delete kiya hua message (jo yaad ho) group ko batao", en: "Tell the group about the last message you deleted (if you remember it)", category: "extreme" },
  { hi: "Group ke kisi member ko unki ek habit batao jo aapko irritate karti hai", en: "Tell a group member one habit of theirs that irritates you", category: "extreme" },
  { hi: "Apne social media pe ek honest status post karo abhi (kuch bhi comfortable wala)", en: "Post an honest status on social media right now (anything you're comfortable with)", category: "extreme" },
  { hi: "Group ko batao aapki phone battery kitni percent hai aur last charge kab ki thi", en: "Tell the group your phone battery percentage and when you last charged it", category: "extreme" },
  { hi: "Apne kisi ek contact ko bina wajah 'we need to talk' message bhejo (turant clarify kar dena)", en: "Send a random contact 'we need to talk' with no context (clarify it's a joke right after)", category: "extreme" },
  { hi: "Group ke kisi member ko unke saamne unki nakal karo 15 second", en: "Mimic a group member in front of their face for 15 seconds", category: "extreme" },
  { hi: "Apna last Google search zor se padho group ko", en: "Read your last Google search out loud to the group", category: "extreme" },
  { hi: "Group ko batao aapke phone mein kitne unread messages hai abhi", en: "Tell the group how many unread messages you currently have", category: "extreme" },
  { hi: "Apna sabse purana WhatsApp status/DP dikhao group ko", en: "Show the group your oldest WhatsApp status/DP", category: "extreme" },
  { hi: "Group ke kisi member ko unki ek galti yaad dilao jo unhone maani thi", en: "Remind a group member of a mistake they once admitted to", category: "extreme" },
  { hi: "Apne phone mein sabse purana photo dhoondke group ko dikhao", en: "Find the oldest photo on your phone and show it to the group", category: "extreme" },
  { hi: "Group ko batao aapne last kisse jhoot bola tha aur kya bola tha", en: "Tell the group who you last lied to and what you said", category: "extreme" },
  { hi: "Apni ek genuine insecurity group ko batao", en: "Tell the group a genuine insecurity of yours", category: "extreme" },
  { hi: "Group ke kisi member ko unke saamne unki weakness point out karo respectfully", en: "Point out a group member's weakness to their face, respectfully", category: "extreme" },
  { hi: "Apna phone ka last unfollowed/unfriended contact batao (bina wajah ke to bhi chalega)", en: "Tell the group the last person you unfollowed/unfriended", category: "extreme" },
  { hi: "Group ko batao aap kisi group member se abhi mafi maangna chahte ho ya nahi, kis baat ke liye", en: "Tell the group if there's a group member you'd want to apologize to, and for what", category: "extreme" },
  { hi: "Apna last message jo aapne kisi se emotionally bheja tha, describe karo (bina naam ke)", en: "Describe the last emotionally heavy message you sent someone (without naming them)", category: "extreme" },
  { hi: "Group ke kisi member ke saath apni ek galatfehmi clear karo abhi (agar hai to)", en: "Clear up a misunderstanding with a group member right now (if there is one)", category: "extreme" },
  { hi: "Apna phone screen time report dikhao group ko", en: "Show the group your phone's screen time report", category: "extreme" },
  { hi: "Group ko batao aapke phone mein sabse zyada kiski photos hai", en: "Tell the group whose photos appear the most on your phone", category: "extreme" },
  { hi: "Apna last saved voice note bina kaate group ko sunao", en: "Play your last saved voice note fully to the group", category: "extreme" },
  { hi: "Group ke kisi member ko unki genuine achievement pe congratulate karo detail mein", en: "Genuinely congratulate a group member on an achievement, in detail", category: "extreme" },
  { hi: "Apna last unsent message jo aapne likha lekin bheja nahi, group ko batao", en: "Tell the group about the last message you typed but never sent", category: "extreme" },
  { hi: "Group ko batao aapko sabse zyada kis group member ki approval chahiye hoti hai", en: "Tell the group whose approval you seek the most among them", category: "extreme" },
  { hi: "Apna phone ka last delete kiya app group ko batao aur kyun delete kiya", en: "Tell the group the last app you deleted and why", category: "extreme" },
  { hi: "Group ke kisi member ko unke bare mein apni asli first impression batao", en: "Tell a group member your genuine first impression of them", category: "extreme" },
  { hi: "Apna last group chat (koi bhi) ka naam group ko batao", en: "Tell the group the name of your last group chat (any one)", category: "extreme" },
  { hi: "Group ko batao aapko is group mein kaun sabse zyada judge karta hai lagta hai", en: "Tell the group who you feel judges you the most in this group", category: "extreme" },
  { hi: "Apna last 'seen' but reply na kiya hua message describe karo", en: "Describe the last message you saw but didn't reply to", category: "extreme" },
  { hi: "Group ke kisi member ke saath apni ek respect wali baat share karo unke bare mein", en: "Share something you genuinely respect about a group member", category: "extreme" },
  { hi: "Apna phone kisi ko do 15 second ke liye unki choice ka koi bhi app kholne", en: "Hand your phone to someone for 15 seconds to open any app of their choice", category: "extreme" },
  { hi: "Group ko batao aap apne aap mein kya sabse zyada change karna chahte ho", en: "Tell the group what you'd want to change most about yourself", category: "extreme" },
  { hi: "Apna last kisi ko diya hua fake excuse group ko batao", en: "Tell the group the last fake excuse you gave someone", category: "extreme" },
  { hi: "Group ke kisi member ko unki genuine strength batao jo aapko lagti hai", en: "Tell a group member a genuine strength of theirs that you notice", category: "extreme" },
  { hi: "Apna last message jo aapne guilt feel karke bheja tha, describe karo", en: "Describe the last message you sent out of guilt", category: "extreme" },
  { hi: "Group ko batao aapko kis cheez se sabse zyada insecurity hoti hai group mein", en: "Tell the group what makes you feel most insecure within this group", category: "extreme" },
  { hi: "Apna phone ka last search history ka topic (comfortable wala) group ko batao", en: "Tell the group the topic of your last search history (comfortable to share)", category: "extreme" },
  { hi: "Group ke kisi member se pucho unhe aapke bare mein kya lagta hai sach mein", en: "Ask a group member what they honestly think of you", category: "extreme" },
  { hi: "Apna last message jo aapne kisi ko block karne se pehle bheja tha, describe karo", en: "Describe the last message you sent before blocking someone", category: "extreme" },
  { hi: "Group ko batao aapko is group mein kaunsi baat sabse zyada annoying lagti hai", en: "Tell the group what annoys you the most in this group", category: "extreme" },
  { hi: "Apna last kisi se maafi maangne wala message dikhao (agar comfortable ho)", en: "Show your last apology message to someone (if comfortable)", category: "extreme" },
  { hi: "Group ke kisi member ko batao unke saath dosti mein aapko kya sabse zyada value lagta hai", en: "Tell a group member what you value most about your friendship with them", category: "extreme" },
  { hi: "Apna last kisi ke saath argument ka topic batao group ko", en: "Tell the group the topic of your last argument with someone", category: "extreme" },
  { hi: "Group ko batao aap apni sabse badi weakness kis tarah hide karte ho doosron se", en: "Tell the group how you hide your biggest weakness from others", category: "extreme" },
  { hi: "Apna last message jo aapne jealousy mein bheja tha, describe karo", en: "Describe the last message you sent out of jealousy", category: "extreme" },
  { hi: "Group ke kisi member ke saamne apni ek genuine galti confess karo unke against", en: "Confess a genuine mistake you made against a group member, to their face", category: "extreme" },
  { hi: "Apna phone ka last liked photo/post kisi bhi platform pe group ko dikhao", en: "Show the group the last photo/post you liked on any platform", category: "extreme" },
  { hi: "Group ko batao aap apni life mein kaunsi baat sabse zyada chhupate ho", en: "Tell the group what you hide the most in your life", category: "extreme" },
  { hi: "Apna last unfollow kiya hua account batao group ko aur kyun kiya", en: "Tell the group the last account you unfollowed and why", category: "extreme" },
  { hi: "Group ke kisi member ko batao unki ek cheez jo aap change dekhna chahte ho", en: "Tell a group member one thing about them you'd want to see change", category: "extreme" },
  { hi: "Apna last kisi ko diya gaya silent treatment batao group ko aur kyun diya", en: "Tell the group about the last time you gave someone the silent treatment and why", category: "extreme" },
  { hi: "Group ko batao aapko kis group member se sabse zyada disappointment hui hai", en: "Tell the group which group member has disappointed you the most", category: "extreme" },
  { hi: "Apna last message jo aapne overthink karke bheja tha, describe karo", en: "Describe the last message you sent after overthinking it", category: "extreme" },
  { hi: "Group ke kisi member ko unki genuine respect batao jo unhone kisi situation mein dikhayi", en: "Tell a group member about the respect they showed in a specific situation", category: "extreme" },
  { hi: "Apna phone ka last delete kiya photo group ko describe karo (bina dikhaye)", en: "Describe (without showing) the last photo you deleted from your phone", category: "extreme" },
  { hi: "Group ko batao aap apni sabse badi galti se kya seekha", en: "Tell the group what you learned from your biggest mistake", category: "extreme" },
  { hi: "Apna last kisi se manga hua maafi wala message group ko dikhao", en: "Show the group the last apology you received from someone", category: "extreme" },
  { hi: "Group ke kisi member ko batao unke saath aapko sabse zyada kab awkward laga tha", en: "Tell a group member when you felt most awkward with them", category: "extreme" },
  { hi: "Apna last kisi ko diya hua compliment jo aapne dil se nahi diya tha, batao", en: "Tell the group about the last compliment you gave that wasn't sincere", category: "extreme" },
  { hi: "Group ko batao aap apni zindagi mein sabse zyada kis wajah se stress mein hote ho", en: "Tell the group what stresses you the most in your life", category: "extreme" },
  { hi: "Apna last group chat mute kiya hua batao group ko aur kyun kiya", en: "Tell the group about the last group chat you muted and why", category: "extreme" },
  { hi: "Group ke kisi member se pucho unhe lagta hai aap genuine ho ya nahi", en: "Ask a group member if they think you're genuine or not", category: "extreme" },
  { hi: "Apna last message jo aapne apni image better dikhane ke liye edit karke bheja tha, batao", en: "Tell the group about the last message you edited to make yourself look better", category: "extreme" },
  { hi: "Group ko batao aap apni sabse badi fear kisi ke saamne kabhi share nahi karte", en: "Tell the group your biggest fear that you never share with anyone", category: "extreme" },
  { hi: "Apna last message jo aapko guilty feel karwata hai, screenshot ke bina describe karo", en: "Describe (without a screenshot) the last message that makes you feel guilty", category: "extreme" },
  { hi: "Group ke kisi member ko batao unke saath aapki dosti mein kya sabse mushkil hai", en: "Tell a group member what's the hardest part of your friendship with them", category: "extreme" },
  { hi: "Apna last kisi ko diya hua false hope batao group ko", en: "Tell the group about the last time you gave someone false hope", category: "extreme" },
  { hi: "Group ko batao aap apni real feelings kis group member se sabse zyada chhupate ho", en: "Tell the group which group member you hide your real feelings from the most", category: "extreme" },
  { hi: "Apna last kisi se maanga gaya favour batao jo aapne wapas nahi kiya", en: "Tell the group about a favor you asked for but never returned", category: "extreme" },
  { hi: "Group ke kisi member ko unki genuine impact batao jo unhone aapki life pe daala", en: "Tell a group member the genuine impact they've had on your life", category: "extreme" },
  { hi: "Apna last message jo aapne khud ko justify karne ke liye bheja tha, describe karo", en: "Describe the last message you sent to justify yourself", category: "extreme" },
  { hi: "Group ko batao aapko apni kaunsi habit sabse zyada change karni hai jo doosron ko affect karti hai", en: "Tell the group which of your habits you most need to change because it affects others", category: "extreme" },
  { hi: "Apna last kisi ke saath toxic behavior ka moment batao group ko", en: "Tell the group about the last time you showed toxic behavior with someone", category: "extreme" },
  { hi: "Group ke kisi member se pucho unhe aapse kya expect hai jo aap abhi tak nahi de paaye", en: "Ask a group member what they expect from you that you haven't delivered yet", category: "extreme" },
  { hi: "Apna last message jo aapne apni jealousy chhupane ke liye likha tha, describe karo", en: "Describe the last message you wrote to hide your jealousy", category: "extreme" },
  { hi: "Group ko batao aap kisi group member ke saath apni asli distance kyun feel karte ho", en: "Tell the group why you feel a real distance with a specific group member", category: "extreme" },
  { hi: "Apna last kisi ko diya hua unfair judgment batao group ko", en: "Tell the group about the last unfair judgment you made about someone", category: "extreme" },
  { hi: "Group ke kisi member ko batao aap unse kya seekhna chahte ho", en: "Tell a group member what you'd want to learn from them", category: "extreme" },
  { hi: "Apna last kisi se kiya gaya vaada batao jo aapne nahi nibhaya", en: "Tell the group about a promise you made but didn't keep", category: "extreme" },
  { hi: "Group ko batao aapko is group ke kisi member se genuinely dar lagta hai kya, kis baat ka", en: "Tell the group if you genuinely feel afraid of any group member, and of what", category: "extreme" },
  { hi: "Apna last message jo aapne apna guilt kam karne ke liye bheja tha, describe karo", en: "Describe the last message you sent to reduce your own guilt", category: "extreme" },
  { hi: "Group ke kisi member ko batao unke saath aapki sabse achhi memory kaunsi hai", en: "Tell a group member your favorite memory with them", category: "extreme" },
  { hi: "Apna last kisi ko diya gaya double standard batao group ko", en: "Tell the group about the last time you showed a double standard toward someone", category: "extreme" },
  { hi: "Group ko batao aap apni sabse badi vulnerability kis group member ke saamne kabhi nahi dikhate", en: "Tell the group your biggest vulnerability that you never show a specific group member", category: "extreme" },

];
